name: mso_dev_dbt_project
version: '1.0.0'
config-version: 2

profile: 'user'

model-paths: ["models"]
test-paths: []  # Disable discovery of external tests
seed-paths: []  # Disable seeds
snapshot-paths: []  # Disable snapshots

models:
  mso_dev_dbt_project:
    staging:
      +materialized: table
    marts:
      +materialized: incremental
      +on_schema_change: sync_all_columns
