name: mso_dev_dbt_project
version: '1.0.0'
config-version: 2
profile: 'user'
model-paths: ["models"]

quoting:
  database: true
  schema: true
  identifier: true

models:
  mso_dev_dbt_project:
    _sources:
      +enabled: false
